version: '3.7'
services:
  example-app:
    image: wesllenalves/example-app
    ports:
      - "8282:80"
    networks:
      - laravel
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == worker
    volumes:
      - type: volume
        source: session-laravel-vol
        target: /var/www/html/storage/framework/sessions
  
  postgres:
    image: postgres:14.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./postgresql
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example_app_docker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - laravel

volumes:
  session-laravel-vol:
    driver: local
    driver_opts:
      type: overlay
      encrypted: "false"

networks: 
  laravel:    
    driver: overlay